### ISSUE TITLE
plugin stores user's CyVerse account password in plain text in browser's persistent storage

### ISSUE THREAD

**Issue by c-mart** [towicode/IJab#8]
CyVerse users choose their account password by hand, and most people have suboptimal password management/reuse habits, so storing this password in plaintext is not a good practice and constitutes a vulnerability ([1](https://www.owasp.org/index.php/Password_Plaintext_Storage), [2](https://cwe.mitre.org/data/definitions/256.html)). Some users probably reuse the same password for their UA NetID. At the very least, can we only keep the password in working memory (as needed to authenticate to iRODS), and prompt the user to enter it with each new session?

Yes, I know the browser only lets sites from the same origin look at the contents of local storage, and this partially mitigates the impact. I'm more concerned about the "unknown unknowns", like:
- The possibility of other vulnerable/malicious code (which could harvest people's credentials) ending up in the same Jupyter Lab/Hub environment.
- The possibility of malicious code ending up on a user's local machine, which then harvests CyVerse credentials from the browser's persistent storage.

![screenshot_2019-01-07_16-19-31](https://user-images.githubusercontent.com/13605043/50799215-5e6c5e00-1298-11e9-9a71-f9ea5422a8a7.jpg)

**Comment by c-mart** [comment]
Has this been fixed by https://github.com/towicode/IJab/commit/10122399b34332021ea0b9806171d8c61d4b16be ?

**Comment by towicode** [comment]
Should be fixed with version 2.0.4
