### ISSUE TITLE
user's CyVerse account password still persists in browser's persistent storage

### ISSUE THREAD

**Issue by c-mart** [towicode/IJab#9]
See issue #8. I upgraded the plugin to the newer version (2.0.4) but key "irpassword" with value of my actual password are still left in my browser storage, basically forever, from the earlier version of the plugin that stored this information. Moreover, it looks like the newer plugin will still use this cached password.

This is an incomplete fix for a serious security issue. The new plugin should clean this up (overwrite/unset `irpassword`), please.

**Comment by towicode** [comment]
Okay this should be overwritten in version 2.0.5.

I will be removing the code to overwrite this local storage item whenever 2.1 is released.

**Comment by c-mart** [comment]
Thank you @towicode, I appreciate the prompt attention :slightly_smiling_face:

I think it's a good idea to leave the overwriting in there ([this](https://github.com/towicode/IJab/commit/97ec515d3fba2b23bfe77552d43ecb065e88c85f#diff-f41e9d04a45c83f3b6f6e630f10117feR120)) basically forever. Imagine that someone used this plugin inside a CyVerse app a couple months ago, but is not currently an active user. if they eventually log in again months/years from now, we may have one chance to remove the secret from their browser storage, and I don't want to miss that opportunity.

(Yes, CyVerse passwords will eventually expire but most people have suboptimal password reuse/rotation habits, so years from now we could still be inadvertently storing their (e.g.) UA NetID password, or their new CyVerse password with only one character changed.)

Does that make sense?
